const EXACT_LABELS: Record<string, string> = {
  address: "Adresse",
  addresscomponent: "Composant d'adresse",
  atm: "Distributeur automatique",
  bed_and_breakfast: "Chambre d'hôtes",
  bus_stop: "Arrêt de bus",
  car_wash: "Station de lavage",
  city_hall: "Mairie",
  clothing_store: "Magasin de vêtements",
  convenience_store: "Supérette",
  department_store: "Grand magasin",
  electronics_store: "Magasin d'électronique",
  fire_station: "Caserne de pompiers",
  food_court: "Aire de restauration",
  furniture_store: "Magasin de meubles",
  gas_station: "Station-service",
  hair_care: "Coiffure",
  hardware_store: "Quincaillerie",
  home_goods_store: "Magasin d'articles ménagers",
  ice_cream_shop: "Glacier",
  light_rail_station: "Station de tramway",
  liquor_store: "Caviste",
  local_government_office: "Administration locale",
  meal_delivery: "Livraison de repas",
  meal_takeaway: "Plats à emporter",
  movie_rental: "Location de films",
  movie_theater: "Cinéma",
  moving_company: "Déménageur",
  night_club: "Discothèque",
  pet_store: "Animalerie",
  post_office: "Bureau de poste",
  primary_school: "École primaire",
  real_estate_agency: "Agence immobilière",
  roofing_contractor: "Couvreur",
  rv_park: "Aire de camping-car",
  secondary_school: "Collège / lycée",
  shoe_store: "Magasin de chaussures",
  shopping_mall: "Centre commercial",
  subway_station: "Station de métro",
  taxi_stand: "Station de taxi",
  tourist_attraction: "Attraction touristique",
  train_station: "Gare",
  transit_station: "Station de transport",
  travel_agency: "Agence de voyage",
  veterinary_care: "Vétérinaire",
  wifi: "Wi-Fi",
  japanese_inn: "Auberge japonaise",
  budget_japanese_inn: "Auberge japonaise économique",
  place_of_worship: "Lieu de culte",
  public_bath: "Bain public",
  skin_care_clinic: "Institut de soins de la peau",
  auto_parts_store: "Magasin de pièces auto",
  car_rental: "Location de voitures",
  car_repair: "Garage automobile",
  car_dealer: "Concessionnaire automobile",
  bike_sharing_station: "Station de vélos en libre-service",
  food_delivery: "Livraison de repas",
  fast_food_restaurant: "Restauration rapide",
  fine_dining_restaurant: "Restaurant gastronomique",
  family_restaurant: "Restaurant familial",
  seafood_restaurant: "Restaurant de fruits de mer",
  asian_restaurant: "Restaurant asiatique",
  asian_fusion_restaurant: "Restaurant fusion asiatique",
  asian_grocery_store: "Épicerie asiatique",
  steak_house: "Steakhouse",
  sushi_restaurant: "Restaurant de sushi",
  vegan_restaurant: "Restaurant végan",
  vegetarian_restaurant: "Restaurant végétarien",
  wine_bar: "Bar à vin",
  sports_club: "Club sportif",
  sports_complex: "Complexe sportif",
  sports_activity_location: "Lieu d'activité sportive",
  adventure_sports_center: "Centre de sports d'aventure",
  amusement_center: "Centre de loisirs",
  event_venue: "Salle d'événements",
  wedding_venue: "Lieu de réception",
  convention_center: "Centre de congrès",
  conference_center: "Centre de conférences",
  business_center: "Centre d'affaires",
  coworking_space: "Espace de coworking",
  corporate_office: "Bureau d'entreprise",
  government_office: "Bureau administratif",
  association_or_organization: "Association ou organisation",
  historical_landmark: "Monument historique",
  cultural_center: "Centre culturel",
  performing_arts_theater: "Théâtre",
  live_music_venue: "Salle de concerts",
  video_arcade: "Salle d'arcade",
  water_park: "Parc aquatique",
  theme_park: "Parc à thème",
  national_park: "Parc national",
  state_park: "Parc régional",
  dog_park: "Parc canin",
  city_park: "Parc urbain",
  wildlife_park: "Parc animalier",
  wildlife_refuge: "Réserve faunique",
  nature_preserve: "Réserve naturelle",
  botanical_garden: "Jardin botanique",
  community_garden: "Jardin communautaire",
  golf_course: "Parcours de golf",
  swimming_pool: "Piscine",
  fitness_center: "Centre de fitness",
  yoga_studio: "Studio de yoga",
  martial_arts_school: "École d'arts martiaux",
  dance_studio: "Studio de danse",
  music_school: "École de musique",
  language_school: "École de langues",
  driving_school: "Auto-école",
  preschool: "École maternelle",
  elementary_school: "École élémentaire",
  middle_school: "Collège",
  high_school: "Lycée",
  private_guest_room: "Chambre d'hôtes privée",
  extended_stay_hotel: "Hôtel long séjour",
  budget_hotel: "Hôtel économique",
  luxury_hotel: "Hôtel de luxe",
  serviced_apartment: "Appart'hôtel",
  apartment_building: "Immeuble d'appartements",
  apartment_complex: "Résidence d'appartements",
  housing_complex: "Complexe résidentiel",
  mobile_home_park: "Parc de mobil-homes",
  rest_stop: "Aire de repos",
  toll_booth: "Péage",
  parking_garage: "Parking couvert",
  parking_lot: "Parking",
  electric_vehicle_charging_station: "Borne de recharge",
  airstrip: "Piste d'atterrissage",
  heliport: "Héliport",
  ferry_terminal: "Terminal de ferry",
  cruise_terminal: "Terminal de croisière",
  bus_station: "Gare routière",
  truck_stop: "Aire de poids lourds",
  rest_area: "Aire de repos",
  acai_shop: "Bar à açaí",
  bagel_shop: "Bagel shop",
  donut_shop: "Donut shop",
  tea_house: "Salon de thé",
  coffee_shop: "Coffee shop",
  juice_shop: "Bar à jus",
  smoothie_shop: "Bar à smoothies",
  chocolate_shop: "Chocolaterie",
  candy_store: "Confiserie",
  cheese_shop: "Fromagerie",
  butcher_shop: "Boucherie",
  fish_market: "Poissonnerie",
  farmers_market: "Marché de producteurs",
  flea_market: "Marché aux puces",
  night_market: "Marché nocturne",
  hypermarket: "Hypermarché",
  discount_store: "Magasin discount",
  outlet_store: "Magasin outlet",
  thrift_store: "Friperie",
  antique_store: "Magasin d'antiquités",
  gift_shop: "Boutique de cadeaux",
  souvenir_shop: "Boutique de souvenirs",
  toy_store: "Magasin de jouets",
  baby_store: "Magasin pour bébés",
  sporting_goods_store: "Magasin d'articles de sport",
  outdoor_store: "Magasin d'activités outdoor",
  camping_store: "Magasin de camping",
  garden_center: "Jardinerie",
  plant_nursery: "Pépinière",
  home_improvement_store: "Magasin de bricolage",
  building_materials_store: "Magasin de matériaux",
  appliance_store: "Magasin d'électroménager",
  mobile_phone_store: "Magasin de téléphonie",
  computer_store: "Magasin informatique",
  video_game_store: "Magasin de jeux vidéo",
  music_store: "Magasin de musique",
  art_supply_store: "Magasin de fournitures artistiques",
  craft_store: "Magasin de loisirs créatifs",
  fabric_store: "Mercerie",
  tailor: "Tailleur",
  dry_cleaner: "Pressing",
  laundromat: "Laverie automatique",
  nail_salon: "Salon de manucure",
  tanning_salon: "Centre de bronzage",
  spa: "Spa",
  massage: "Massage",
  chiropractor: "Chiropracteur",
  dentist: "Dentiste",
  doctor: "Médecin",
  hospital: "Hôpital",
  pharmacy: "Pharmacie",
  drugstore: "Pharmacie",
  medical_lab: "Laboratoire médical",
  physiotherapist: "Kinésithérapeute",
  psychologist: "Psychologue",
  optician: "Opticien",
  ophthalmologist: "Ophtalmologue",
  dermatologist: "Dermatologue",
  pediatrician: "Pédiatre",
  gynecologist: "Gynécologue",
  veterinarian: "Vétérinaire",
  animal_shelter: "Refuge pour animaux",
  pet_boarding: "Pension pour animaux",
  dog_day_care: "Garderie pour chiens",
  bar_and_grill: "Bar-grill",
  beer_garden: "Brasserie en plein air",
  brewpub: "Brasserie-artisanale",
  wine_store: "Caviste",
  distillery: "Distillerie",
  winery: "Domaine viticole",
  vineyard: "Vignoble",
  farm: "Ferme",
  ranch: "Ranch",
  orchard: "Verger",
  stable: "Écurie",
  barber_shop: "Barbier",
  beauty_salon: "Salon de beauté",
  body_art_service: "Tatouage / piercing",
  astrologer: "Astrologue",
  psychic: "Voyant",
  fortune_teller: "Voyant",
  wedding_planner: "Organisateur de mariage",
  photographer: "Photographe",
  florist: "Fleuriste",
  caterer: "Traiteur",
  bakery: "Boulangerie",
  cafe: "Café",
  cafeteria: "Cafétéria",
  bar: "Bar",
  restaurant: "Restaurant",
  bistro: "Bistro",
  brewery: "Brasserie",
  buffet_restaurant: "Restaurant buffet",
  brunch_restaurant: "Restaurant brunch",
  breakfast_restaurant: "Restaurant petit-déjeuner",
  barbecue_restaurant: "Restaurant barbecue",
  barbecue_area: "Espace barbecue",
  banquet_hall: "Salle de banquet",
  auditorium: "Auditorium",
  amphitheatre: "Amphithéâtre",
  arena: "Arène",
  stadium: "Stade",
  gym: "Salle de sport",
  park: "Parc",
  beach: "Plage",
  bridge: "Pont",
  zoo: "Zoo",
  aquarium: "Aquarium",
  museum: "Musée",
  library: "Bibliothèque",
  church: "Église",
  mosque: "Mosquée",
  synagogue: "Synagogue",
  hindu_temple: "Temple hindou",
  buddhist_temple: "Temple bouddhiste",
  cemetery: "Cimetière",
  courthouse: "Tribunal",
  embassy: "Ambassade",
  police: "Police",
  bank: "Banque",
  airport: "Aéroport",
  campground: "Camping",
  bowling_alley: "Bowling",
  casino: "Casino",
  amusement_park: "Parc d'attractions",
  art_gallery: "Galerie d'art",
  art_museum: "Musée d'art",
  art_studio: "Atelier d'art",
  book_store: "Librairie",
  bicycle_store: "Magasin de vélos",
  accounting: "Comptabilité",
  insurance_agency: "Agence d'assurance",
  lawyer: "Avocat",
  electrician: "Électricien",
  plumber: "Plombier",
  painter: "Peintre",
  locksmith: "Serrurier",
  laundry: "Laverie",
  storage: "Stockage",
  store: "Magasin",
  school: "École",
  university: "Université",
  archipelago: "Archipel",
  academic_department: "Département universitaire",
  aircraft_rental_service: "Location d'avions",
};

const TOKEN_LABELS: Record<string, string> = {
  acai: "açaí",
  accounting: "comptabilité",
  address: "adresse",
  adventure: "aventure",
  afghani: "afghan",
  african: "africain",
  american: "américain",
  amusement: "loisirs",
  apartment: "appartement",
  aquarium: "aquarium",
  arena: "arène",
  argentinian: "argentin",
  art: "art",
  asian: "asiatique",
  association: "association",
  astrologer: "astrologue",
  athletic: "sportif",
  australian: "australien",
  austrian: "autrichien",
  auto: "automobile",
  bagel: "bagel",
  bakery: "boulangerie",
  bangladeshi: "bangladais",
  bank: "banque",
  banquet: "banquet",
  bar: "bar",
  barbecue: "barbecue",
  barber: "barbier",
  basque: "basque",
  bavarian: "bavarois",
  beach: "plage",
  beautician: "esthéticienne",
  beauty: "beauté",
  bed: "chambre",
  beer: "bière",
  belgian: "belge",
  bicycle: "vélo",
  bike: "vélo",
  bistro: "bistro",
  body: "corporel",
  book: "livre",
  botanical: "botanique",
  bowling: "bowling",
  brazilian: "brésilien",
  breakfast: "petit-déjeuner",
  brewery: "brasserie",
  brewpub: "brasserie-artisanale",
  bridge: "pont",
  british: "britannique",
  brunch: "brunch",
  buddhist: "bouddhiste",
  budget: "économique",
  buffet: "buffet",
  building: "bâtiment",
  burmese: "birman",
  burrito: "burrito",
  bus: "bus",
  business: "affaires",
  butcher: "boucherie",
  cafe: "café",
  cafeteria: "cafétéria",
  cajun: "cajun",
  camp: "camping",
  campground: "camping",
  car: "voiture",
  care: "soins",
  casino: "casino",
  catering: "traiteur",
  center: "centre",
  centre: "centre",
  cemetery: "cimetière",
  chicken: "poulet",
  chinese: "chinois",
  chocolate: "chocolat",
  church: "église",
  city: "ville",
  clinic: "clinique",
  clothing: "vêtements",
  club: "club",
  coffee: "café",
  college: "université",
  comedy: "comédie",
  community: "communautaire",
  complex: "complexe",
  component: "composant",
  concert: "concert",
  conference: "conférence",
  convention: "congrès",
  cooking: "cuisine",
  corporate: "entreprise",
  courthouse: "tribunal",
  cream: "crème",
  cultural: "culturel",
  dance: "danse",
  day: "jour",
  deli: "traiteur",
  delivery: "livraison",
  department: "département",
  dessert: "dessert",
  diner: "diner",
  dining: "restauration",
  discount: "discount",
  distillery: "distillerie",
  dog: "chien",
  donut: "beignet",
  doughnut: "beignet",
  driving: "conduite",
  drug: "médicament",
  drugstore: "pharmacie",
  electric: "électrique",
  electrician: "électricien",
  electronics: "électronique",
  embassy: "ambassade",
  emergency: "urgence",
  equipment: "équipement",
  estate: "immobilier",
  event: "événement",
  extended: "long",
  factory: "usine",
  family: "familial",
  farm: "ferme",
  farmers: "producteurs",
  fashion: "mode",
  fast: "rapide",
  ferry: "ferry",
  field: "terrain",
  fine: "gastronomique",
  fire: "pompiers",
  fish: "poisson",
  fitness: "fitness",
  flea: "puces",
  flight: "vol",
  florist: "fleuriste",
  food: "alimentation",
  football: "football",
  forest: "forêt",
  french: "français",
  funeral: "funéraire",
  furniture: "meubles",
  fusion: "fusion",
  gallery: "galerie",
  garden: "jardin",
  gas: "carburant",
  german: "allemand",
  gift: "cadeaux",
  golf: "golf",
  government: "gouvernement",
  grocery: "épicerie",
  guest: "hôte",
  gym: "sport",
  hair: "coiffure",
  hall: "salle",
  hardware: "quincaillerie",
  health: "santé",
  heliport: "héliport",
  high: "secondaire",
  hindu: "hindou",
  historical: "historique",
  home: "maison",
  hospital: "hôpital",
  hostel: "auberge",
  hotel: "hôtel",
  house: "maison",
  housing: "logement",
  ice: "glace",
  indian: "indien",
  inn: "auberge",
  insurance: "assurance",
  international: "international",
  internet: "internet",
  island: "île",
  italian: "italien",
  japanese: "japonais",
  jewelry: "bijoux",
  juice: "jus",
  karaoke: "karaoké",
  korean: "coréen",
  lake: "lac",
  landmark: "monument",
  laser: "laser",
  latin: "latin",
  laundry: "laverie",
  law: "droit",
  lawyer: "avocat",
  league: "ligue",
  lebanese: "libanais",
  library: "bibliothèque",
  light: "léger",
  liquor: "alcool",
  live: "live",
  local: "local",
  lodging: "hébergement",
  lounge: "lounge",
  mall: "centre commercial",
  marina: "marina",
  market: "marché",
  martial: "martial",
  massage: "massage",
  meal: "repas",
  medical: "médical",
  mediterranean: "méditerranéen",
  memorial: "mémorial",
  mexican: "mexicain",
  middle: "moyen",
  mobile: "mobile",
  monument: "monument",
  mosque: "mosquée",
  motel: "motel",
  motorcycle: "moto",
  mountain: "montagne",
  moving: "déménagement",
  museum: "musée",
  music: "musique",
  nail: "ongles",
  national: "national",
  natural: "naturel",
  nature: "nature",
  night: "nuit",
  noodle: "nouilles",
  office: "bureau",
  organization: "organisation",
  oriental: "oriental",
  outlet: "outlet",
  park: "parc",
  parking: "parking",
  parts: "pièces",
  performing: "spectacle",
  persian: "persan",
  pet: "animal",
  pharmacy: "pharmacie",
  photo: "photo",
  pier: "jetée",
  pizza: "pizza",
  place: "lieu",
  planetarium: "planétarium",
  plant: "plantes",
  playground: "jeux",
  plumber: "plombier",
  police: "police",
  pool: "piscine",
  port: "port",
  post: "poste",
  preschool: "maternelle",
  primary: "primaire",
  private: "privé",
  pub: "pub",
  public: "public",
  rail: "rail",
  ramen: "ramen",
  ranch: "ranch",
  real: "immobilier",
  recording: "enregistrement",
  recreation: "loisirs",
  regional: "régional",
  rental: "location",
  repair: "réparation",
  resort: "resort",
  rest: "repos",
  restaurant: "restaurant",
  retail: "vente",
  river: "rivière",
  roofing: "toiture",
  room: "chambre",
  rv: "camping-car",
  salon: "salon",
  sandwich: "sandwich",
  school: "école",
  science: "science",
  seafood: "fruits de mer",
  secondary: "secondaire",
  service: "service",
  sharing: "partage",
  shipping: "expédition",
  shoe: "chaussures",
  shop: "boutique",
  shopping: "shopping",
  ski: "ski",
  skin: "peau",
  smoothie: "smoothie",
  snack: "snack",
  soccer: "football",
  social: "social",
  spa: "spa",
  spanish: "espagnol",
  specialty: "spécialité",
  sporting: "sport",
  sports: "sport",
  stadium: "stade",
  state: "régional",
  station: "gare",
  stay: "séjour",
  steak: "steak",
  stop: "arrêt",
  storage: "stockage",
  store: "magasin",
  studio: "studio",
  subway: "métro",
  supermarket: "supermarché",
  sushi: "sushi",
  swimming: "natation",
  synagogue: "synagogue",
  taco: "taco",
  tailer: "tailleur",
  takeaway: "emporter",
  tanning: "bronzage",
  tattoo: "tatouage",
  taxi: "taxi",
  tea: "thé",
  technology: "technologie",
  temple: "temple",
  tennis: "tennis",
  terminal: "terminal",
  thai: "thaïlandais",
  theater: "théâtre",
  theatre: "théâtre",
  theme: "thème",
  thrift: "friperie",
  toll: "péage",
  tour: "tour",
  tourist: "touristique",
  tower: "tour",
  toy: "jouets",
  train: "train",
  transit: "transport",
  transport: "transport",
  travel: "voyage",
  truck: "poids lourds",
  turkish: "turc",
  university: "université",
  vegan: "végan",
  vegetarian: "végétarien",
  vehicle: "véhicule",
  veterinary: "vétérinaire",
  video: "vidéo",
  vietnamese: "vietnamien",
  vineyard: "vignoble",
  visitor: "visiteur",
  warehouse: "entrepôt",
  water: "eau",
  wedding: "mariage",
  wellness: "bien-être",
  western: "western",
  wholesaler: "grossiste",
  wifi: "wi-fi",
  wildlife: "faune",
  wine: "vin",
  winery: "vignoble",
  worship: "culte",
  yoga: "yoga",
  zoo: "zoo",
  and: "et",
  or: "ou",
  of: "de",
  for: "pour",
  grill: "grill",
  goods: "articles",
  materials: "matériaux",
  improvement: "bricolage",
  eastern: "oriental",
  activity: "activité",
  location: "lieu",
  venue: "lieu",
  arts: "arts",
  supply: "fournitures",
  supplies: "fournitures",
  contractor: "entrepreneur",
  agency: "agence",
  company: "entreprise",
  space: "espace",
  area: "espace",
  preserve: "réserve",
  refuge: "refuge",
  observatory: "observatoire",
  laboratory: "laboratoire",
  research: "recherche",
  innovation: "innovation",
  information: "information",
  attraction: "attraction",
  attractions: "attractions",
  mini: "mini",
  go: "go",
  kart: "kart",
  escape: "escape",
  game: "game",
  games: "jeux",
  arcade: "arcade",
  trampoline: "trampoline",
  climbing: "escalade",
  hiking: "randonnée",
  trail: "sentier",
  course: "parcours",
  court: "court",
  pitch: "terrain",
  ground: "terrain",
  gymnasium: "gymnase",
  physiotherapist: "kinésithérapeute",
  chiropractor: "chiropracteur",
  ophthalmologist: "ophtalmologue",
  gynecologist: "gynécologue",
  pediatrician: "pédiatre",
  dermatologist: "dermatologue",
  psychologist: "psychologue",
  optician: "opticien",
};

const CUISINE_ADJECTIVES = new Set([
  "afghani",
  "african",
  "american",
  "argentinian",
  "australian",
  "austrian",
  "bangladeshi",
  "basque",
  "bavarian",
  "belgian",
  "brazilian",
  "british",
  "burmese",
  "cajun",
  "chinese",
  "french",
  "german",
  "greek",
  "indian",
  "indonesian",
  "italian",
  "japanese",
  "korean",
  "lebanese",
  "mediterranean",
  "mexican",
  "middle",
  "persian",
  "spanish",
  "thai",
  "turkish",
  "vietnamese",
  "asian",
  "european",
  "latin",
]);

function translateToken(token: string): string {
  return TOKEN_LABELS[token] ?? token.replace(/-/g, " ");
}

function capitalizeFrench(text: string): string {
  if (!text) return text;
  return text.charAt(0).toUpperCase() + text.slice(1);
}

function translateRestaurantTechName(tokens: string[]): string | null {
  if (tokens[tokens.length - 1] !== "restaurant") return null;

  if (tokens.length === 1) return "Restaurant";

  const prefixTokens = tokens.slice(0, -1);

  if (
    prefixTokens.length === 2 &&
    prefixTokens[0] === "middle" &&
    prefixTokens[1] === "eastern"
  ) {
    return "Restaurant moyen-oriental";
  }

  if (
    prefixTokens.length === 2 &&
    prefixTokens[0] === "asian" &&
    prefixTokens[1] === "fusion"
  ) {
    return "Restaurant fusion asiatique";
  }

  if (prefixTokens.length === 1 && CUISINE_ADJECTIVES.has(prefixTokens[0])) {
    return `Restaurant ${translateToken(prefixTokens[0])}`;
  }

  if (prefixTokens.length === 1) {
    return `Restaurant ${translateToken(prefixTokens[0])}`;
  }

  const translated = prefixTokens.map(translateToken).join(" ");
  return `Restaurant ${translated}`;
}

function translateStoreTechName(tokens: string[]): string | null {
  if (tokens[tokens.length - 1] !== "store") return null;
  if (tokens.length === 1) return "Magasin";

  if (tokens.length >= 2 && tokens[tokens.length - 2] === "grocery") {
    const prefixTokens = tokens.slice(0, -2);
    if (prefixTokens.length === 0) return "Épicerie";
    const translated = prefixTokens.map(translateToken).join(" ");
    return `Épicerie ${translated}`;
  }

  const prefixTokens = tokens.slice(0, -1);
  const translated = prefixTokens.map(translateToken).join(" ");

  if (prefixTokens.length === 1) {
    return `Magasin de ${translated}`;
  }

  return capitalizeFrench(`${translated} — magasin`);
}

function translateCenterTechName(tokens: string[]): string | null {
  if (
    tokens[tokens.length - 1] !== "center" &&
    tokens[tokens.length - 1] !== "centre"
  ) {
    return null;
  }

  if (tokens.length === 1) return "Centre";

  const prefixTokens = tokens.slice(0, -1);
  const translated = prefixTokens.map(translateToken).join(" ");
  return `Centre ${translated}`;
}

function translateStationTechName(tokens: string[]): string | null {
  if (tokens[tokens.length - 1] !== "station") return null;
  if (tokens.length === 1) return "Gare";

  const prefixTokens = tokens.slice(0, -1);
  const translated = prefixTokens.map(translateToken).join(" ");
  return `Station de ${translated}`;
}

function translateParkTechName(tokens: string[]): string | null {
  if (tokens[tokens.length - 1] !== "park") return null;
  if (tokens.length === 1) return "Parc";

  const prefixTokens = tokens.slice(0, -1);
  const translated = prefixTokens.map(translateToken).join(" ");
  return `Parc ${translated}`;
}

function translateMuseumTechName(tokens: string[]): string | null {
  if (tokens[tokens.length - 1] !== "museum") return null;
  if (tokens.length === 1) return "Musée";

  const prefixTokens = tokens.slice(0, -1);
  const translated = prefixTokens.map(translateToken).join(" ");
  return `Musée ${translated}`;
}

function translateGalleryTechName(tokens: string[]): string | null {
  if (tokens[tokens.length - 1] !== "gallery") return null;
  if (tokens.length === 1) return "Galerie";

  const prefixTokens = tokens.slice(0, -1);
  const translated = prefixTokens.map(translateToken).join(" ");
  return `Galerie ${translated}`;
}

function translateServiceTechName(tokens: string[]): string | null {
  if (tokens[tokens.length - 1] !== "service") return null;
  if (tokens.length === 1) return "Service";

  const prefixTokens = tokens.slice(0, -1);
  const translated = prefixTokens.map(translateToken).join(" ");
  return `Service de ${translated}`;
}

function translateShopTechName(tokens: string[]): string | null {
  if (tokens[tokens.length - 1] !== "shop") return null;
  if (tokens.length === 1) return "Boutique";

  const prefixTokens = tokens.slice(0, -1);
  const translated = prefixTokens.map(translateToken).join(" ");
  return `Boutique ${translated}`;
}

export function techNameToFrenchDisplayName(techName: string): string {
  const normalized = techName.trim().toLowerCase();
  if (!normalized) return "";

  if (EXACT_LABELS[normalized]) {
    return EXACT_LABELS[normalized];
  }

  const tokens = normalized.split("_").filter(Boolean);

  const patternTranslators = [
    translateRestaurantTechName,
    translateStoreTechName,
    translateCenterTechName,
    translateStationTechName,
    translateParkTechName,
    translateMuseumTechName,
    translateGalleryTechName,
    translateServiceTechName,
    translateShopTechName,
  ];

  for (const translate of patternTranslators) {
    const translated = translate(tokens);
    if (translated) return capitalizeFrench(translated);
  }

  const fallback = tokens.map(translateToken).join(" ");
  return capitalizeFrench(fallback);
}
