import type { Metadata } from "next";
import { Urbanist, Poppins } from 'next/font/google'
import "./globals.css";
import AppShell from "@/app/AppShell";

const urbanist = Urbanist({
  subsets: ['latin'],
  variable: '--font-urbanist',
  display: 'swap',
})

const poppins = Poppins({
  weight: ['400', '500', '600'],
  subsets: ['latin'],
  variable: '--font-poppins',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fr">
      <body className={`${poppins.variable} ${urbanist.variable} antialiased bg-red-500`}>
        <AppShell>
          {children}
        </AppShell>
      </body>
    </html>
  );
}